server {
    listen 6622;
    server_name localhost;

    root /var/www/kyonshi.com;
    index index.html;

    location / {
        try_files $uri $uri/ /favicons$uri =404;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    location = /README.md {
        internal;
    }
}