server {
    listen 6622;
    server_name localhost;

    root /var/www/kyonshi.com;
    index index.html;

    location = /contact {
        return 301 /#contact;
    }

    location = /links {
        return 301 /#links;
    }

    location = /profile {
        return 301 /#about;
    }

    location = /top {
        return 301 /;
    }

    location / {
        try_files $uri $uri/ /favicons$uri =404;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }
}